CREATE DATABASE `Wikinamek`;
-- Create Categories Table
CREATE TABLE `category` (
  `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(255) NOT NULL
);
-- Create Tags Table
CREATE TABLE `tags` (
  `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(255) NOT NULL
);
-- Create Users Table
CREATE TABLE `user` (
  `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('reader','author','admin') NOT NULL
);

-- CreateWikis Table
CREATE TABLE `wiki` (
  `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `content` text NOT NULL,
  `creation_date` date NOT NULL,
  `status` enum('pending','approved','denied','archived','deleted') NOT NULL,
  `author_id` int NOT NULL,
  `category_id` int NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user(id),
  FOREIGN KEY (category_id) REFERENCES category(id)
);
-- Create Pivot Wiki_tags Table
CREATE TABLE `wiki_tag` (
  `tag_id` int NOT NULL,
  `wiki_id` int NOT NULL,
  FOREIGN KEY (tag_id) REFERENCES tags(id),
  FOREIGN KEY (wiki_id) REFERENCES wiki(id)
);

--Populate the Categories Table 
INSERT INTO `category` (`name`) VALUES
('Science'),
('Literature'),
('Technology'),
('Art'),
('Philosophy'),
('Music'),
('Food'),
('Health'),
('Fitness'),
('Psychology'),
('Education'),
('Astronomy'),
('Environment'),
('Politics'),
('Economics'),
('Sociology'),
('Languages'),
('DIY');

--Populate the Tags Table 
INSERT INTO `tags` (`name`) VALUES
('Technology'),
('Science'),
('Programming'),
('Art'),
('Music'),
('Nature'),
('Travel'),
('Food'),
('Fitness'),
('Health'),
('Fashion'),
('Design'),
('Gaming'),
('Books'),
('Movies'),
('Sports'),
('Photography'),
('History'),
('Education'),
('Business'),
('Finance'),
('Cooking'),
('DIY'),
('Hiking'),
('Pets'),
('Automobiles'),
('Space'),
('Fitness'),
('Hobbies'),
('Crafts'),
('Entertainment'),
('Anime'),
('Memes'),
('Politics'),
('News'),
('Podcasts'),
('Comedy'),
('Writing'),
('Poetry'),
('Mindfulness'),
('Productivity'),
('Coding'),
('WebDevelopment'),
('MobileApps'),
('ArtificialIntelligence'),
('VirtualReality'),
('AugmentedReality'),
('Blockchain'),
('Cryptocurrency'),
('Environment'),
('FitnessMotivation'),
('HealthyEating'),
('Vegetarian'),
('Vegan'),
('WeightLoss'),
('PhotographyLovers'),
('Adventure'),
('LuxuryTravel'),
('StreetFood'),
('HealthyRecipes'),
('FashionStyle'),
('InteriorDesign'),
('GamingCommunity'),
('ClassicMovies'),
('Soccer'),
('Basketball'),
('Baseball'),
('ScienceFiction'),
('NaturePhotography'),
('EducationForAll'),
('SmallBusiness'),
('Entrepreneurship'),
('Investing'),
('CookingAdventures'),
('DIYProjects'),
('CampingLife'),
('PetLovers'),
('CarEnthusiasts'),
('SpaceExploration'),
('YogaJourney'),
('TechNews'),
('Futurism'),
('AIInnovation'),
('VirtualRealityWorld'),
('CryptocurrencyInvesting'),
('EnvironmentalAwareness'),
('WorkoutMotivation'),
('BookLovers'),
('MindfulLiving'),
('WebDesign'),
('MobileAppDevelopment'),
('MachineLearning'),
('VRGaming'),
('BlockchainRevolution'),
('HealthyLiving'),

